trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  EC2_IP: '3.26.213.217'   # replace with your EC2 public IP
  EC2_USER: 'ubuntu'

stages:

# ===================== BUILD STAGE =====================
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Build Stage"
      displayName: 'Echo Build Stage'


# ===================== TEST STAGE =====================
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: TestJob
    steps:
    - script: echo "Test Stage"
      displayName: 'Echo Test Stage'


# ===================== DEPLOY STAGE =====================
- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Test
  jobs:
  - job: DeployJob
    steps:

    - task: DownloadSecureFile@1
      name: sshKey
      inputs:
        secureFile: 'Data Analytics.pem'

    - script: |
        chmod 600 $(sshKey.secureFilePath)

        sed -i 's/__EC2_IP__/$(EC2_IP)/g' index.html

        scp -o StrictHostKeyChecking=no \
          -i $(sshKey.secureFilePath) \
          index.html \
          $(EC2_USER)@$(EC2_IP):/var/www/html/index.html

        ssh -o StrictHostKeyChecking=no \
          -i $(sshKey.secureFilePath) \
          $(EC2_USER)@$(EC2_IP) \
          "sudo systemctl restart httpd"

        echo "Deploy Stage — index.html deployed and Apache restarted"
      displayName: 'Deploy to EC2 via SSH'